/** Explicit public text, paired with its status. Adding an internal error never publishes its message implicitly. */
export const PUBLIC_ERRORS: Readonly<Record<number, readonly string[]>> = {
	400: [
		"Choose the operation to release",
		"Unsupported repository lifecycle input",
		"Type the repository name to confirm deletion",
		"Type the namespace handle to confirm deletion",
		"Observation enabled flag required",

		"Invalid page limit",
		"Artifact content required",
		"Attach a hosted fork first",
		"Attached execution context required",
		"Base required",
		"Canonical storage missing",
		"Changes required",
		"Choose a published revision",
		"Concern unavailable",
		"Connection required",
		"Exact base revision required",
		"Execution context required",
		"Grant requires a namespace member or team",
		"Git pack checksum mismatch",
		"Head required",
		"Head revision required",
		"Invalid Git pack",
		"Invalid JSON",
		"Invalid storage identity",
		"Mutation requires an idempotency key",
		"Namespace and repository required",
		"Namespace required",
		"Operation identity required",
		"Pairing proof required",
		"Pushed fork branch required",
		"Reason required",
		"Reconnect this agent",
		"Repository not initialized",
		"Repository required",
		"Resolution reason required",
		"Retained commit unavailable",
		"Retained storage identity unavailable",
		"Retained storage ref unavailable",
		"Retained tree unavailable",
		"Review index required",
		"Review reason required",
		"Revision required",
		"Source path required",
		"Source repository unavailable",
		"Source storage missing",
		"Subject required",
		"Team members must belong to the namespace",
		"Unsupported Git request",
		"Unsupported Git route",
		"Unsupported repository command",
		"Upstream unavailable",
		"Verification kind required",
		"Verification summary required",
		"Workspace title required",
	],
	401: [
		"Access identity invalid or expired",
		"Git authentication required",
		"Git requires a Cruce connection",
		"Invalid Git credentials",
		"Reconnect this agent",
		"Session invalid",
		"Sign in again",
		"Sign in through Cloudflare Access",
		"Sign in to initialize your Cruce identity",
		"Terminal authorization expired",
		"Terminal authorization required",
	],
	403: [
		"Human namespace owner required",
		"Cleanup recovery authorization unavailable; retry from an authorized connection",
		"Agent capability denied",
		"Agent writers require a dedicated Cruce worktree or clone",
		"Agents cannot attest human verification",
		"Canonical writes require reviewed human promotion",
		"Console access required",
		"Git read scope required",
		"Git write scopes required",
		"Human bridge workspace scope denied",
		"Human maintainer approval required",
		"Human namespace maintainer required",
		"Human repository maintainer required",
		"Identity changed",
		"Identity origin mismatch",
		"Invitation invalid or expired",
		"Invitation not permitted",
		"Namespace access denied",
		"Namespace mismatch",
		"Namespace ownership cannot be changed through membership",
		"Only owners appoint maintainers",
		"Only owners change maintainers",
		"Only your own unfinished terminal workspace can be renewed",
		"Pairing request expired",
		"Pairing request invalid",
		"Propose a published revision from your own workspace",
		"Protected paths require a repository maintainer",
		"Read scope required",
		"Repository access denied",
		"Repository identity mismatch",
		"Repository maintainer required",
		"Repository mismatch",
		"Repository not authorized for this agent connection",
		"Repository write permission required",
		"Resource policy denies this operation",
		"Same-origin request required",
		"Terminal Git scope denied",
		"Terminal workspace scope denied",
		"Workspace belongs to another user",
	],
	404: [
		"Repository unavailable",
		"Artifact cache unavailable; inspect the retained artifact source",
		"Artifact unavailable",
		"Artifacts repository unavailable",
		"Change unavailable",
		"Cloudflare could not find the requested storage.",
		"File unavailable at this exact revision",
		"Namespace unavailable",
		"Not found",
		"Record unavailable",
		"Resource reservation unavailable",
		"Retained history unavailable",
		"Source cache unavailable; explicitly recover retained source",
		"Source unavailable; publish committed source first",
		"User unavailable",
		"Workspace unavailable",
	],
	405: ["GET required", "POST required"],
	409: [
		"Repository is read-only",
		"Repository retirement has blockers",
		"Namespace deletion has blockers",
		"Confirm that Cruce will not delete this namespace's legacy storage",
		"Confirm that Cruce will not delete this repository's legacy storage",
		"Storage is reachable; delete without forgetting it",
		"Namespace is being deleted",
		"Resume the existing namespace deletion",
		"Delete every repository before the namespace",
		"A personal namespace belongs to its account; delete its repositories instead",
		"Repository deletion is already authorized",
		"Resume the existing repository deletion",
		"Resume the repository deletion instead",
		"Retry the unfinished repository transition",
		"Fork parent identity changed",
		"Observation subscription identity changed",
		"Observation subscription is disabled",
		"Observation recovery must finish before enabling a new configuration",
		"Observation provider identity changed",
		"Observation installation identity changed",
		"Observation fork parent is unavailable",
		"Observed canonical differs from accepted history; reconcile canonical before promotion",

		"Retained operation result unavailable; restore its recorded state before retrying",
		"Retention proof unavailable; recover or inspect source before cleanup",
		"Directory layout exceeds the supported conversion limit",
		"Resource reservation was released; use a new operation identity",
		"Coordination storage capacity reached; inspect retained records before adding work",
		"Namespace record capacity reached; inspect retained records before adding work",
		"Repository record capacity reached; inspect retained records before adding work",
		"Namespace discovery capacity reached",
		"Namespace handle allocation limit reached",
		"Resume the existing authorized cleanup operation",
		"Uncertain resource reservations cannot be released",
		"Fork ref inventory exceeds the cleanup limit",
		"Base revision changed; refresh and propose the reconciled revision",
		"Change is closed or promotion is in progress",
		"Human approval required for this revision",
		"Review concern requires a reasoned human resolution",
		"No retained fork",
		"Artifacts repository address mismatch",
		"Artifacts repository already exists; retry the same operation",
		"Artifacts repository identity changed",
		"Artifacts repository ownership mismatch",
		"Attach an execution context first",
		"Canonical Git repository is not ready",
		"Canonical moved; reconcile source and obtain fresh review",
		"Canonical provider identity changed; promotion refused",
		"Canonical repository is already set up",
		"Canonical repository unavailable",
		"Change is not open",
		"Checkout already reserved by another workspace; end or detach that workspace first",
		"Cloudflare reported a conflicting change. Retry the same operation.",
		"Creation key reused",
		"End the workspace before cleaning up its fork",
		"Evidence must name the base or a published workspace revision",
		"Evidence retry differs from its recorded commit",
		"Evidence revision mismatch",
		"Exact reviewed source unavailable",
		"Existing connected-account storage requires an explicit storage transition by the administrator",
		"Fork identity changed; cleanup refused",
		"Fork identity changed; publication refused",
		"Fork ownership mismatch",
		"Fork ownership or parent mismatch",
		"Fork ref moved; publish its exact current revision",
		"Fork unavailable",
		"Git source object is unavailable",
		"Git source object type differs from its graph",
		"Installation storage account mismatch",
		"Installation storage identity changed; restore the recorded configuration",
		"Installation storage is unavailable; contact the administrator",
		"Integrate the review base with Git before publishing",
		"Namespace handle already used",
		"Namespace identity mismatch",
		"No execution is attached",
		"Operation identity reused",
		"Personal namespaces have one owner; create a shared namespace to collaborate",
		"Promotion failed; reconcile source and obtain fresh review",
		"Promotion is blocked; inspect the change readiness checklist",
		"Promotion outcome differs from the exact candidate; reconcile source and obtain fresh review",
		"Promotion requires a non-forced forward update",
		"Provider repository identity unavailable",
		"Published commits must descend from the workspace baseline and previous publication",
		"Pushed source graph is incomplete",
		"Reconcile the pending promotion before another canonical update",
		"Recorded Artifacts repository is missing",
		"Recorded provider repository identities disagree",
		"Recorded storage identity is unavailable; administrator reconciliation required",
		"Repository name already used",
		"Repository setup retry differs from its recorded commit",
		"Resource operation identity reused",
		"Retained artifact ref differs from the recorded revision",
		"Retained commit differs from the exact revision",
		"Retained publication ref differs from its exact revision",
		"Retained source graph is incomplete; recovery refused",
		"Retained source provider identity changed; promotion refused",
		"Retained source provider identity changed; publication refused",
		"Retained source ref differs from the recorded revision",
		"Retained storage identity changed",
		"Review base must name the workspace baseline or observed upstream revision",
		"Review base objects unavailable; fetch upstream first",
		"Review must name the open change's exact revision",
		"Set up the canonical repository first",
		"Teams belong to shared namespaces",
		"Terminal authorization is bound to an existing workspace",
		"Unretained fork refs; publish their commits before cleanup",
		"Verification must name the exact revision",
		"Verification requires an open change",
		"A change from this workspace is being promoted",
		"Workspace has ended",
		"Workspace is attached to a different execution context",
		"Workspace is attached to another execution context; detach it first",
	],
	413: [
		"Observation ref inventory exceeds its limit",
		"Observation subscription inventory exceeds its limit",

		"Git ref advertisement exceeds the inspection limit",
		"Coordination record exceeds its byte limit",
		"Coordination state exceeds its byte limit; inspect capacity before adding work",
		"Directory lookup exceeds its entry limit",
		"Diff tree exceeds the inspection limit",
		"File is too large for inline source inspection",
		"Git source exceeds the bounded cache limit; use normal Git for larger repositories",
		"Git source exceeds the expanded object limit",
		"Git source exceeds the object traversal limit",
		"Git transfer exceeds the 32 MiB gateway limit",
		"Request too large",
		"Source exceeds inline inspection limits; request a smaller file",
		"Source inspection exceeds its provider-call limit",
		"Source inspection exceeds its provider-call limit; choose an exact published revision",
		"Source inspection exceeds its response limit",
		"Source tree exceeds the inspection limit",
		"Source tree exceeds the inspection limit; request a file path",
	],
	415: ["Binary file; inline source unavailable"],
	502: [
		"Artifacts Git request failed",
		"Artifacts operation unavailable; retry the same operation identity",
		"Artifacts source read unavailable",
		"Cloudflare could not complete the request. Retry the same operation.",
		"Cloudflare rejected storage access. Ask the installation administrator to check Artifacts permissions.",
		"Invalid Artifacts Git remote",
	],
	410: ["Repository has been deleted", "Namespace has been deleted"],
	503: [
		"Repository lifecycle unavailable",
		"Observation installation is not configured",
		"Observation subscription service unavailable",
		"Observation subscription inventory is incomplete",
		"Observation subscription creation is uncertain",

		"Access identity verification unavailable; retry",
		"Configure Cloudflare Access identity for Cruce",
		"Git cache reset unavailable",
		"Identity encryption not configured",
		"Invalid Access issuer",
		"OAuth unavailable",
		"Provider source inspection unavailable",
		"Repository token inventory is incomplete; cleanup cannot be confirmed",
		"Repository token reconciliation needs another retry",
	],
	429: [
		"Artifacts operation unavailable; retry the same operation identity",
		"Cloudflare is rate limiting requests. Retry the same operation shortly.",
	],
};
